version: "3"
services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"

  postgresql:
    image: postgres:15.4
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: lab4
      POSTGRES_USER: sleeter
      POSTGRES_PASSWORD: 1234567
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - postgresql_bd_net

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.6
    restart: always
    env_file:
      - config.env
    ports:
      - "8081:80"
    volumes:
      - pgadmin-data:/var/lib/pgAdmin
    networks:
      - postgresql_bd_net

  backend:
    container_name: backend
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    environment:
      POSTGRES_SERVER: postgresql
      POSTGRES_PORT: 5432
      POSTGRES_DB: lab4
      POSTGRES_USER: sleeter
      POSTGRES_PASSWORD: 1234567
    networks:
      - postgresql_bd_net


networks:
  postgresql_bd_net:
    driver: bridge

volumes:
  postgresql-data:
  pgadmin-data: